### ISSUE TITLE
URL metadata non genera nulla

### ISSUE THREAD

**Issue by avalli** [WPGov/wp-spid-italia#33]
Il debug.log contiene queste segnalazioni

[17-Apr-2022 10:53:35 UTC] PHP Deprecated:  contextual_help è <strong>deprecata</strong> dalla versione 3.3.0! Al suo posto utilizza get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab(). in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/functions.php on line 5698
[17-Apr-2022 10:53:35 UTC] PHP Deprecated:  define() è stato chiamato con un argomento <strong>deprecato</strong> dalla versione 4.0.0! La costante WPLANG nel tuo file wp-config.php non è più necessaria.. in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/functions.php on line 5607
[17-Apr-2022 10:53:40 UTC] PHP Deprecated:  contextual_help è <strong>deprecata</strong> dalla versione 3.3.0! Al suo posto utilizza get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab(). in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/functions.php on line 5698
[17-Apr-2022 10:53:43 UTC] PHP Deprecated:  contextual_help è <strong>deprecata</strong> dalla versione 3.3.0! Al suo posto utilizza get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab(). in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/functions.php on line 5698
[17-Apr-2022 10:53:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getSPMetadata() on bool in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-content/plugins/wp-spid-italia/wp-spid-italia.php:56
Stack trace:

#0 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/class-wp-hook.php(307): {closure}()
#1 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-includes/plugin.php(474): WP_Hook->do_action()
#3 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-settings.php(587): do_action()
#4 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-config.php(106): require_once('/web/htdocs/www...')
#5 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-load.php(50): require_once('/web/htdocs/www...')
#6 /web/htdocs/www.nonsolovela.org/home/wordpress/wp-blog-header.php(13): require_once('/web/htdocs/www...')
#7 /web/htdocs/www.nonsolovela.org/home/wordpress/index.php(17): require('/web/htdocs/www...')
#8 {main}
  thrown in /web/htdocs/www.nonsolovela.org/home/wordpress/wp-content/plugins/wp-spid-italia/wp-spid-italia.php on line 56

**Comment by milesimarco** [comment]
Buongiorno,
verifichi che nelle impostazioni del plugin siano compilati tutti i campi e che il plugin sia aggiornato all'ultima versione.
